# Generated by Django 5.1.2 on 2024-10-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TempApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temphistory',
            name='time_created',
            field=models.IntegerField(),
        ),
    ]
